syntax on

" Map 'jj' to escape in insert mode
inoremap jj <Esc>

set tabstop=4
set softtabstop=4
set shiftwidth=4
set autoindent
set smartindent
set smarttab
set expandtab

set nowrap

set cursorline
set number
set relativenumber
set scrolloff=8
set signcolumn=yes

set showcmd
set conceallevel=1
