#!/bin/sh
GREEN='\033[0;32m'
BRIGHT_GREEN='\033[1;32m'
NC='\033[0m' # No Color

printf '%b\n' "$GREEN"
printf '%s\n' "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
printf '%s\n' "░                                                            ░"
# Note: Using cat << "EOF" to preserve those Unicode diagonal lines
cat << "EOF"
░       ___        __      _  _         _    _               ░
░      ╱ _ ╲__  __╱ _│_ __│ ││ │  _ __ │ │ _(_) ___          ░
░     │ │ │ ╲ ╲╱ ╱ │_│ '__│ ││ │_│ '_ ╲│ │╱ ╱ │╱ _ ╲         ░
░     │ │_│ │>  <│  _│ │  │__   _│ │ │ │   <│ │  __╱         ░
░      ╲___╱╱_╱╲_╲_│ │_│     │_│ │_│ │_│_│╲_╲_│╲___│         ░
EOF
printf '%s\n' "░                                                            ░"
printf '%s\n' "░                      [ ACCESS GRANTED ]                    ░"
printf '%b\n' "░                  Welcome back, ${BRIGHT_GREEN}0xfr4nkie!${GREEN}                  ░"
printf '%s\n' "░                                                            ░"
printf '%s\n' "░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░"
printf '%b\n' "$NC"